# Render Port
server.port=${PORT:5432}

# PostgreSQL
spring.datasource.url=${https://axonix-1.onrender.com}
spring.datasource.username=${axonix_db_yvm5_user}
spring.datasource.password=${vAfszTpHPrayKPu16efI65s07qUeNilm}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Performance
spring.main.lazy-initialization=true
spring.jpa.open-in-view=false

# Logging
logging.level.root=WARN

# Hikari Pool
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

# Teacher Passcode
teacher.passcode=${TEACHER_PASSCODE}

# Gemini API
gemini.api.key=${GEMINI_API_KEY}